/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingAplicationsRouteImport } from './routes/training-aplications'
import { Route as TradeReportsRouteImport } from './routes/trade-reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HorsesRouteImport } from './routes/horses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingAplicationsNewRouteImport } from './routes/training-aplications.new'
import { Route as TrainingAplicationsTrainingAplicationIdRouteImport } from './routes/training-aplications/$trainingAplicationId'
import { Route as TradeReportsNewRouteImport } from './routes/trade-reports.new'
import { Route as TradeReportsTradeReportIdRouteImport } from './routes/trade-reports/$tradeReportId'
import { Route as HorsesNewRouteImport } from './routes/horses.new'
import { Route as HorsesHorseIdRouteImport } from './routes/horses/$horseId'

const TrainingAplicationsRoute = TrainingAplicationsRouteImport.update({
  id: '/training-aplications',
  path: '/training-aplications',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeReportsRoute = TradeReportsRouteImport.update({
  id: '/trade-reports',
  path: '/trade-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesRoute = HorsesRouteImport.update({
  id: '/horses',
  path: '/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingAplicationsNewRoute = TrainingAplicationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TrainingAplicationsRoute,
} as any)
const TrainingAplicationsTrainingAplicationIdRoute =
  TrainingAplicationsTrainingAplicationIdRouteImport.update({
    id: '/$trainingAplicationId',
    path: '/$trainingAplicationId',
    getParentRoute: () => TrainingAplicationsRoute,
  } as any)
const TradeReportsNewRoute = TradeReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TradeReportsRoute,
} as any)
const TradeReportsTradeReportIdRoute =
  TradeReportsTradeReportIdRouteImport.update({
    id: '/$tradeReportId',
    path: '/$tradeReportId',
    getParentRoute: () => TradeReportsRoute,
  } as any)
const HorsesNewRoute = HorsesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HorsesRoute,
} as any)
const HorsesHorseIdRoute = HorsesHorseIdRouteImport.update({
  id: '/$horseId',
  path: '/$horseId',
  getParentRoute: () => HorsesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horses': typeof HorsesRouteWithChildren
  '/login': typeof LoginRoute
  '/trade-reports': typeof TradeReportsRouteWithChildren
  '/training-aplications': typeof TrainingAplicationsRouteWithChildren
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses/new': typeof HorsesNewRoute
  '/trade-reports/$tradeReportId': typeof TradeReportsTradeReportIdRoute
  '/trade-reports/new': typeof TradeReportsNewRoute
  '/training-aplications/$trainingAplicationId': typeof TrainingAplicationsTrainingAplicationIdRoute
  '/training-aplications/new': typeof TrainingAplicationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horses': typeof HorsesRouteWithChildren
  '/login': typeof LoginRoute
  '/trade-reports': typeof TradeReportsRouteWithChildren
  '/training-aplications': typeof TrainingAplicationsRouteWithChildren
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses/new': typeof HorsesNewRoute
  '/trade-reports/$tradeReportId': typeof TradeReportsTradeReportIdRoute
  '/trade-reports/new': typeof TradeReportsNewRoute
  '/training-aplications/$trainingAplicationId': typeof TrainingAplicationsTrainingAplicationIdRoute
  '/training-aplications/new': typeof TrainingAplicationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horses': typeof HorsesRouteWithChildren
  '/login': typeof LoginRoute
  '/trade-reports': typeof TradeReportsRouteWithChildren
  '/training-aplications': typeof TrainingAplicationsRouteWithChildren
  '/horses/$horseId': typeof HorsesHorseIdRoute
  '/horses/new': typeof HorsesNewRoute
  '/trade-reports/$tradeReportId': typeof TradeReportsTradeReportIdRoute
  '/trade-reports/new': typeof TradeReportsNewRoute
  '/training-aplications/$trainingAplicationId': typeof TrainingAplicationsTrainingAplicationIdRoute
  '/training-aplications/new': typeof TrainingAplicationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/horses'
    | '/login'
    | '/trade-reports'
    | '/training-aplications'
    | '/horses/$horseId'
    | '/horses/new'
    | '/trade-reports/$tradeReportId'
    | '/trade-reports/new'
    | '/training-aplications/$trainingAplicationId'
    | '/training-aplications/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/horses'
    | '/login'
    | '/trade-reports'
    | '/training-aplications'
    | '/horses/$horseId'
    | '/horses/new'
    | '/trade-reports/$tradeReportId'
    | '/trade-reports/new'
    | '/training-aplications/$trainingAplicationId'
    | '/training-aplications/new'
  id:
    | '__root__'
    | '/'
    | '/horses'
    | '/login'
    | '/trade-reports'
    | '/training-aplications'
    | '/horses/$horseId'
    | '/horses/new'
    | '/trade-reports/$tradeReportId'
    | '/trade-reports/new'
    | '/training-aplications/$trainingAplicationId'
    | '/training-aplications/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HorsesRoute: typeof HorsesRouteWithChildren
  LoginRoute: typeof LoginRoute
  TradeReportsRoute: typeof TradeReportsRouteWithChildren
  TrainingAplicationsRoute: typeof TrainingAplicationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training-aplications': {
      id: '/training-aplications'
      path: '/training-aplications'
      fullPath: '/training-aplications'
      preLoaderRoute: typeof TrainingAplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-reports': {
      id: '/trade-reports'
      path: '/trade-reports'
      fullPath: '/trade-reports'
      preLoaderRoute: typeof TradeReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses': {
      id: '/horses'
      path: '/horses'
      fullPath: '/horses'
      preLoaderRoute: typeof HorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-aplications/new': {
      id: '/training-aplications/new'
      path: '/new'
      fullPath: '/training-aplications/new'
      preLoaderRoute: typeof TrainingAplicationsNewRouteImport
      parentRoute: typeof TrainingAplicationsRoute
    }
    '/training-aplications/$trainingAplicationId': {
      id: '/training-aplications/$trainingAplicationId'
      path: '/$trainingAplicationId'
      fullPath: '/training-aplications/$trainingAplicationId'
      preLoaderRoute: typeof TrainingAplicationsTrainingAplicationIdRouteImport
      parentRoute: typeof TrainingAplicationsRoute
    }
    '/trade-reports/new': {
      id: '/trade-reports/new'
      path: '/new'
      fullPath: '/trade-reports/new'
      preLoaderRoute: typeof TradeReportsNewRouteImport
      parentRoute: typeof TradeReportsRoute
    }
    '/trade-reports/$tradeReportId': {
      id: '/trade-reports/$tradeReportId'
      path: '/$tradeReportId'
      fullPath: '/trade-reports/$tradeReportId'
      preLoaderRoute: typeof TradeReportsTradeReportIdRouteImport
      parentRoute: typeof TradeReportsRoute
    }
    '/horses/new': {
      id: '/horses/new'
      path: '/new'
      fullPath: '/horses/new'
      preLoaderRoute: typeof HorsesNewRouteImport
      parentRoute: typeof HorsesRoute
    }
    '/horses/$horseId': {
      id: '/horses/$horseId'
      path: '/$horseId'
      fullPath: '/horses/$horseId'
      preLoaderRoute: typeof HorsesHorseIdRouteImport
      parentRoute: typeof HorsesRoute
    }
  }
}

interface HorsesRouteChildren {
  HorsesHorseIdRoute: typeof HorsesHorseIdRoute
  HorsesNewRoute: typeof HorsesNewRoute
}

const HorsesRouteChildren: HorsesRouteChildren = {
  HorsesHorseIdRoute: HorsesHorseIdRoute,
  HorsesNewRoute: HorsesNewRoute,
}

const HorsesRouteWithChildren =
  HorsesRoute._addFileChildren(HorsesRouteChildren)

interface TradeReportsRouteChildren {
  TradeReportsTradeReportIdRoute: typeof TradeReportsTradeReportIdRoute
  TradeReportsNewRoute: typeof TradeReportsNewRoute
}

const TradeReportsRouteChildren: TradeReportsRouteChildren = {
  TradeReportsTradeReportIdRoute: TradeReportsTradeReportIdRoute,
  TradeReportsNewRoute: TradeReportsNewRoute,
}

const TradeReportsRouteWithChildren = TradeReportsRoute._addFileChildren(
  TradeReportsRouteChildren,
)

interface TrainingAplicationsRouteChildren {
  TrainingAplicationsTrainingAplicationIdRoute: typeof TrainingAplicationsTrainingAplicationIdRoute
  TrainingAplicationsNewRoute: typeof TrainingAplicationsNewRoute
}

const TrainingAplicationsRouteChildren: TrainingAplicationsRouteChildren = {
  TrainingAplicationsTrainingAplicationIdRoute:
    TrainingAplicationsTrainingAplicationIdRoute,
  TrainingAplicationsNewRoute: TrainingAplicationsNewRoute,
}

const TrainingAplicationsRouteWithChildren =
  TrainingAplicationsRoute._addFileChildren(TrainingAplicationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HorsesRoute: HorsesRouteWithChildren,
  LoginRoute: LoginRoute,
  TradeReportsRoute: TradeReportsRouteWithChildren,
  TrainingAplicationsRoute: TrainingAplicationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
